#!/bin/bash
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
source_root="$repo_root/test/fixtures/image_corpus/image"
reference_root="$repo_root/test/fixtures/image_corpus/references/imagemagick"

if ! command -v magick >/dev/null; then
  echo 'ImageMagick 7 (magick) is required.' >&2
  exit 1
fi

rm -rf "$reference_root"
mkdir -p "$reference_root/png" "$reference_root/apng"

# Normalize independently decoded first frames to non-paletted RGBA8888 PNG.
# Tests can then read these with a simple PNG decoder without repeating the
# source codec implementation under test.
for source in "$source_root"/png/basi*.png "$source_root"/png/basn*.png; do
  name="$(basename "$source")"
  magick "${source}[0]" -alpha on -depth 8 "PNG32:$reference_root/png/$name"
done

for name in test_apng.png test_apng1.png test_apng3.png test_apng4.png; do
  magick "$source_root/png/apng/${name}[0]" \
    -alpha on -depth 8 "PNG32:$reference_root/apng/$name"
done

{
  echo 'Generated by:'
  magick -version | head -n 2
} > "$reference_root/GENERATOR.txt"

echo "Wrote $(find "$reference_root" -type f | wc -l | tr -d ' ') reference files."
