import 'dart:convert';
import 'dart:io';

const _scriptName = 'tool/update_browser_corpus_manifest.dart';
const _corpusRoot = 'test/fixtures/image_corpus/image';
const _outputPath = 'test/support/image_corpus_manifest.dart';

void main(List<String> arguments) {
  if (arguments.length > 1 ||
      (arguments.isNotEmpty && arguments.single != '--check')) {
    throw ArgumentError('Usage: dart run $_scriptName [--check]');
  }
  final checkOnly = arguments.isNotEmpty;
  final groups = <String, List<String>>{
    'imageCorpusJpegFixtures': _files('jpg', '.jpg'),
    'imageCorpusPngFixtures': _files('png', '.png'),
    'imageCorpusApngFixtures': _files('png/apng', '.png'),
    'imageCorpusBrokenPngFixtures': _files('png/broken', '.png'),
    'imageCorpusGifFixtures': _files('gif', '.gif'),
    'imageCorpusWebpFixtures': _files('webp', '.webp'),
    'imageCorpusTiffFixtures': _files('tiff', '.tif'),
    'imageCorpusBmpFixtures': _files('bmp', '.bmp'),
    'imageCorpusIcoFixtures': _files('ico', '.ico'),
  };

  const expectedCounts = <String, int>{
    'imageCorpusJpegFixtures': 62,
    'imageCorpusPngFixtures': 188,
    'imageCorpusApngFixtures': 5,
    'imageCorpusBrokenPngFixtures': 4,
    'imageCorpusGifFixtures': 12,
    'imageCorpusWebpFixtures': 30,
    'imageCorpusTiffFixtures': 26,
    'imageCorpusBmpFixtures': 10,
    'imageCorpusIcoFixtures': 3,
  };
  for (final entry in expectedCounts.entries) {
    final actual = groups[entry.key]!.length;
    if (actual != entry.value) {
      throw StateError(
        '${entry.key} contains $actual fixtures; expected ${entry.value}. '
        'Review the corpus and update expectations intentionally.',
      );
    }
  }

  final output = StringBuffer()
    ..writeln('// Generated by tool/update_browser_corpus_manifest.dart.')
    ..writeln('// Do not edit by hand.')
    ..writeln();
  for (final entry in groups.entries) {
    output.writeln('const ${entry.key} = <String>[');
    for (final path in entry.value) {
      output.writeln('  ${jsonEncode(path)},');
    }
    output
      ..writeln('];')
      ..writeln();
  }

  final generated = '${output.toString().trimRight()}\n';
  final fixtureCount = groups.values.fold<int>(
    0,
    (sum, files) => sum + files.length,
  );
  final outputFile = File(_outputPath);
  if (checkOnly) {
    if (!outputFile.existsSync() ||
        outputFile.readAsStringSync() != generated) {
      throw StateError(
        '$_outputPath is stale. Run `dart run $_scriptName` and commit it.',
      );
    }
    stdout.writeln('Verified $_outputPath with $fixtureCount source fixtures.');
    return;
  }

  outputFile.parent.createSync(recursive: true);
  outputFile.writeAsStringSync(generated);
  stdout.writeln('Wrote $_outputPath with $fixtureCount source fixtures.');
}

List<String> _files(String relativeDirectory, String extension) {
  final directory = Directory('$_corpusRoot/$relativeDirectory');
  final files =
      directory
          .listSync()
          .whereType<File>()
          .where((file) => file.path.toLowerCase().endsWith(extension))
          .map(
            (file) => file.path
                .replaceAll('\\', '/')
                .replaceFirst('$_corpusRoot/', ''),
          )
          .toList()
        ..sort();
  return files;
}
